url: localhost:4000/index.html
pygments: true
markdown: kramdown
excerpt_separator: <!--more-->
headers : 
 - 
    img : nevis.jpg
    title : Ben Nevis, Lochaber, Scotland
    caption : Shadow of Ben Nevis at dawn after a night ascent Of Tower Ridge. March 2014
 -
    img : dione_view.jpg
    title : Dione, Tantalus Range, British Columbia
    caption : The view from the summit of Dione. June 2012
 - 
    img : fairfield.jpg
    title : The Fairfield Horseshoe, Cumbria
    caption : Chris and Helen on the Fairfield Horseshoe in the Lake District
 - 
    img : aonach_eagach.jpg
    title : The Aonach Eagach, Glencoe, Scotland
    caption : Climber on the Aonach Eagach ridge during one of the snowiest winters of recent times. January 2014
 - 
    img : cormac_serratus.jpg
    title : Serratus, Tantalus Range, British Columbia
    caption : Cormac Flynn on the summit of Serratus. June 2012
 -
    img : traprain.jpg
    title : Traprain Law, Midlothian, Scotland
    caption : Climbers on Traprain Law late one Summer evening. July 2013
 -
    img : pointe_lachenal.jpg
    title : Pointe Lachenal and the Triangle du Tacul. Chamonix, France
    caption : My first climbing in the Alps, July 2013
