name: Generate and deploy website

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        
      - name: Install Python Prerequisites
        run: |
          set -euo pipefail
          python -m pip install pip --upgrade
          pip install -r requirements.txt --upgrade
          pip install ./wasm_demo

      - name: Install emcripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install

      - name: Generate website locally only
        if: ${{ !(endsWith(github.ref, '/master')) }}
        run: |
            set -euo pipefail
            echo "Generate ${{ github.ref }}"
            invoke build
        working-directory: algodynamic
          
      - name: Generate and publish website
        if: ${{ endsWith(github.ref, '/master') }}
        run: |
            set -euo pipefail
            echo "Publish ${{ github.ref }}"
            invoke publish
        working-directory: algodynamic
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

